version: '3.8'

services:
  douyin-upload:
    image: douyinup
    container_name: douyin-upload-auto1
    ports:
      - "0.0.0.0:4990:5000"    # Web界面端口
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
      - DOCKER_ENV=true
      - DISPLAY=:99
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    volumes:
      # 工作区目录
      - .:/app
      # 数据持久化目录
      - /vol1/1000/docker/playwright-browser1/cookie:/app/cookie
      - /vol1/1000/docker/playwright-browser1/videos:/app/videos
      - /vol1/1000/docker/playwright-browser1/downloads:/app/downloads
      - /vol1/1000/docker/playwright-browser1/database:/app/database
      - /vol1/1000/docker/playwright-browser1/logs:/app/logs
      # Playwright缓存
      - playwright-cache:/ms-playwright
    working_dir: /app
    networks:
      - douyin-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  playwright-cache:

networks:
  douyin-net:
    driver: bridge