version: '3.8'

services:
  douyin-upload:
    image: douyin-upload:latest
    container_name: douyin-upload-auto
    ports:
      - "0.0.0.0:5000:5000"    # Web界面端口
      - "0.0.0.0:4701:4701"    # 额外服务端口
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
      - DOCKER_ENV=true
      - DISPLAY=:99
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    volumes:
      - .:/workspace
      - /vol1/1000/docker/playwright-browser/cookie:/workspace/cookie
      - /vol1/1000/docker/playwright-browser/videos:/workspace/videos
      - /vol1/1000/docker/playwright-browser/downloads:/workspace/downloads
      - /vol1/1000/docker/playwright-browser/database:/workspace/database
      - /vol1/1000/docker/playwright-browser/logs:/workspace/logs
      - playwright-cache:/ms-playwright
    working_dir: /workspace
    command: >
      bash -c "
        echo 'Installing system dependencies...' &&
        apt-get update && apt-get install -y ffmpeg &&
        echo 'Installing main dependencies...' &&
        pip install -r requirements.txt &&
        echo 'Installing Downloader dependencies...' &&
        pip install -r Downloader/requirements.txt &&
        echo 'Installing Playwright browsers...' &&
        npx playwright install chromium &&
        echo 'Starting application...' &&
        python app.py
      "
    networks:
      - douyin-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  playwright-cache:

networks:
  douyin-net:
    driver: bridge